"""v1 baseline schema

Revision ID: 11b6aee1380f
Revises: 
Create Date: 2026-06-13 13:02:39.344299

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '11b6aee1380f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_rule_sets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_filter_rule_sets_one_active', 'filter_rule_sets', ['is_active'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_state',
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('realized_pnl_usd', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('unrealized_pnl_usd', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('open_positions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trades_taken', sa.Integer(), server_default='0', nullable=False),
    sa.Column('kill_switch_on', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trading_day')
    )
    op.create_table('symbols',
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), server_default='NASDAQ', nullable=False),
    sa.Column('listed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('filter_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_set_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_key', sa.Text(), nullable=False),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('op', sa.Enum('lt', 'le', 'gt', 'ge', 'eq', 'between', 'in', 'contains_any', 'contains_none', 'within_minutes', name='rule_op'), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('severity', sa.Text(), server_default='hard', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("severity IN ('hard','soft')", name='ck_filter_rules_severity'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['filter_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_filter_rules_set', 'filter_rules', ['rule_set_id'], unique=False)
    op.create_table('news',
    sa.Column('newsid', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('storyurl', sa.Text(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('newsid')
    )
    op.create_index('idx_news_symbol_datetime', 'news', ['symbol', 'datetime'], unique=False)
    op.create_table('scanner_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('widget', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('strategy_label', sa.Text(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('volume_today', sa.BigInteger(), nullable=True),
    sa.Column('float_shares', sa.BigInteger(), nullable=True),
    sa.Column('rel_vol_today', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rel_vol_5min', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rel_gap', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('rel_gain_loss', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('short_interest', sa.BigInteger(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scanner_events_day', 'scanner_events', ['trading_day'], unique=False)
    op.create_index('idx_scanner_events_strategy_ts', 'scanner_events', ['strategy', 'ts'], unique=False)
    op.create_index('idx_scanner_events_symbol_ts', 'scanner_events', ['symbol', 'ts'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('first_alert_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('widgets_fired', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('strategies_fired', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_5_pillars', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_close_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('last_volume', sa.BigInteger(), nullable=True),
    sa.Column('last_float', sa.BigInteger(), nullable=True),
    sa.Column('last_rel_vol_today', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_rel_vol_5min', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_rel_gap', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('last_rel_gain', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('last_short_interest', sa.BigInteger(), nullable=True),
    sa.Column('has_news', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('latest_newsid', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('passed', 'failed_filter', 'stale', name='candidate_status'), server_default='passed', nullable=False),
    sa.Column('failed_rules', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['latest_newsid'], ['news.newsid'], ),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidates_cooldown', 'candidates', ['cooldown_until'], unique=False)
    op.create_index('idx_candidates_day_status', 'candidates', ['trading_day', 'status'], unique=False)
    op.create_index('idx_candidates_symbol_day', 'candidates', ['symbol', 'trading_day'], unique=False)
    op.create_table('filter_evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_set_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_key', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('observed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['filter_rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_filter_evaluations_candidate', 'filter_evaluations', ['candidate_id'], unique=False)
    op.create_table('trade_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('position_size', sa.Integer(), nullable=False),
    sa.Column('max_risk_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'filled', 'closed', 'cancelled', name='trade_plan_status'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ibkr_order_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("side IN ('long','short')", name='ck_trade_plans_side'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_plan_id', sa.BigInteger(), nullable=True),
    sa.Column('ibkr_order_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('order_type', sa.Text(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.ForeignKeyConstraint(['trade_plan_id'], ['trade_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ibkr_order_id')
    )
    op.create_table('fills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fills')
    op.drop_table('orders')
    op.drop_table('trade_plans')
    op.drop_index('idx_filter_evaluations_candidate', table_name='filter_evaluations')
    op.drop_table('filter_evaluations')
    op.drop_index('idx_candidates_symbol_day', table_name='candidates')
    op.drop_index('idx_candidates_day_status', table_name='candidates')
    op.drop_index('idx_candidates_cooldown', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('idx_scanner_events_symbol_ts', table_name='scanner_events')
    op.drop_index('idx_scanner_events_strategy_ts', table_name='scanner_events')
    op.drop_index('idx_scanner_events_day', table_name='scanner_events')
    op.drop_table('scanner_events')
    op.drop_index('idx_news_symbol_datetime', table_name='news')
    op.drop_table('news')
    op.drop_index('idx_filter_rules_set', table_name='filter_rules')
    op.drop_table('filter_rules')
    op.drop_table('symbols')
    op.drop_table('session_state')
    op.drop_table('risk_events')
    op.drop_index('idx_filter_rule_sets_one_active', table_name='filter_rule_sets', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('filter_rule_sets')
    # ### end Alembic commands ###
