"""engine: engine_runs, engine_events, bar_aggregates + slippage cols on fills

Revision ID: 1f588b56d403
Revises: 11b6aee1380f
Create Date: 2026-06-14 08:06:06.545800

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1f588b56d403'
down_revision: str | None = '11b6aee1380f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('instrument_type', sa.Text(), nullable=False),
    sa.Column('strategy_name', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_caps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autonomous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('market_data_type', sa.Text(), nullable=False),
    sa.Column('ibkr_client_id', sa.Integer(), nullable=False),
    sa.Column('ibkr_account', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('starting', 'running', 'stopping', 'stopped', 'error', name='engine_run_status'), server_default='starting', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('trades_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_engine_runs_started_at', 'engine_runs', ['started_at'], unique=False)
    op.create_index('idx_engine_runs_status', 'engine_runs', ['status'], unique=False)
    op.create_table('bar_aggregates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('macd_line', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['engine_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bar_aggregates_run_ts', 'bar_aggregates', ['run_id', 'ts'], unique=True)
    op.create_table('engine_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Enum('bar', 'indicator', 'signal', 'decision', 'risk_block', 'ready_for_approval', 'approval_granted', 'approval_rejected', 'order_submit', 'order_status', 'fill', 'position_open', 'position_close', 'slippage', 'error', 'engine_start', 'engine_stop', 'ibkr_connected', 'ibkr_disconnected', name='engine_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['engine_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_engine_events_run_ts', 'engine_events', ['run_id', 'ts'], unique=False)
    op.create_index('idx_engine_events_type', 'engine_events', ['event_type'], unique=False)
    op.add_column('fills', sa.Column('engine_run_id', sa.BigInteger(), nullable=True))
    op.add_column('fills', sa.Column('signal_price', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('fills', sa.Column('signal_ts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fills', sa.Column('slippage_cents', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('fills', sa.Column('slippage_bps', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('fills', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fills', 'engine_runs', ['engine_run_id'], ['id'])
    op.add_column('orders', sa.Column('engine_run_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'orders', 'engine_runs', ['engine_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'engine_run_id')
    op.drop_constraint(None, 'fills', type_='foreignkey')
    op.drop_column('fills', 'latency_ms')
    op.drop_column('fills', 'slippage_bps')
    op.drop_column('fills', 'slippage_cents')
    op.drop_column('fills', 'signal_ts')
    op.drop_column('fills', 'signal_price')
    op.drop_column('fills', 'engine_run_id')
    op.drop_index('idx_engine_events_type', table_name='engine_events')
    op.drop_index('idx_engine_events_run_ts', table_name='engine_events')
    op.drop_table('engine_events')
    op.drop_index('idx_bar_aggregates_run_ts', table_name='bar_aggregates')
    op.drop_table('bar_aggregates')
    op.drop_index('idx_engine_runs_status', table_name='engine_runs')
    op.drop_index('idx_engine_runs_started_at', table_name='engine_runs')
    op.drop_table('engine_runs')
    # ### end Alembic commands ###
